CREATE TEMP TABLE RESULTS as
SELECT
  RULE_ID,
  DATE(TIMESTAMP(EXECUTION_TIME)) AS EXECUTION_DATE,
  MAX(RESULT_ID) AS RESULT_ID,
  MAX(TOTAL_RECORDS) AS TOTAL_RECORDS,
  MAX(FAILED_RECORDS) AS FAILED_RECORDS,
  MAX(PASSED_PERCENTAGE) AS PASSED_PERCENTAGE,
  MAX(STATUS) AS STATUS,
  MAX(DETAILS) AS DETAILS
FROM `cf-esproapro-bic-pro-ou.SH_REP.FACT_DQ_RESULTS`
GROUP BY
  RULE_ID,
  EXECUTION_DATE;

CREATE OR REPLACE TABLE cf-esproapro-bic-pro-ou.SH_REP.CUBE_DQ as
SELECT
a.*, 
b.RULE_NAME, 
b.RULE_DESCRIPTION, 
b.TARGET_TABLE, 
b.SQL_CONDITION, 
b.SEVERITY, 
b.THRESHOLD, 
b.ACTIVE, 
b.CREATED_AT, 
b.UPDATED_AT, 
b.TABLE, 
b.TABLE_FIELD, 
b.TABLE_SOURCE, 
b.MASTER
FROM RESULTS a
LEFT JOIN cf-esproapro-bic-pro-ou.SH_REP.DIM_DQ_RULES b on a.RULE_ID = b.RULE_ID